CREATE TABLE IF NOT EXISTS tasks (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT,
	date_target DATETIME,
	date_start DATETIME DEFAULT CURRENT_TIMESTAMP,
	archived BOOLEAN DEFAULT FALSE
);

