CREATE TABLE IF NOT EXISTS milestones (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	task INTEGER NOT NULL,
	type TEXT,
	value INTEGER,
	achieved DATE,
	message TEXT,
	FOREIGN KEY (task) REFERENCES tasks (id)
);

